import { SystemModel } from '../core/model.js';

export function generateOtelSchema(data: SystemModel): string {
  const otelSchema = {
    $schema: "http://json-schema.org/draft-07/schema#",
    title: `${data.system}-OpenTelemetry-Attributes-Schema`,
    description: `OpenTelemetry semantic attributes validation schema generated by OpenAgentModel for system ${data.system} (v${data.version}).`,
    type: "object",
    properties: {
      resource: {
        type: "object",
        properties: {
          "service.name": { const: data.system },
          "service.version": { const: data.version }
        },
        required: ["service.name"]
      },
      spans: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: {
              type: "string",
              enum: ["agent.run", "agent.tool_call", "agent.delegate"]
            },
            attributes: {
              type: "object",
              properties: {
                "gen_ai.system": { const: data.system },
                "gen_ai.agent.id": {
                  type: "string",
                  enum: (data.agents || []).map((a) => a.id)
                },
                "gen_ai.tool.id": {
                  type: "string",
                  enum: (data.tools || []).map((t) => t.id)
                },
                "gen_ai.tool.risk": {
                  type: "string",
                  enum: ["low", "medium", "high", "critical"]
                },
                "gen_ai.mcp.id": {
                  type: "string",
                  enum: (data.mcp_servers || []).map((m) => m.id)
                },
                "gen_ai.mcp.trust_level": {
                  type: "string",
                  enum: ["internal", "partner", "external", "untrusted"]
                }
              },
              required: ["gen_ai.system"]
            }
          },
          required: ["name", "attributes"]
        }
      }
    },
    required: ["resource", "spans"]
  };

  return JSON.stringify(otelSchema, null, 2);
}
